services:
  redis:
    image: redis:latest
    volumes:
      - ./redis_data:/data
    networks:
      - internal

  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers", "--workers", "4"]

    stdin_open: true
    tty: true

    networks:
      - internal

volumes:
  redis_data:

networks:
  internal:
    driver: bridge
