services:
  # Using redis for auth
  redis:
    image: redis/redis-stack:latest
    ports:
    # - outside: inside
      - 6379:6379
      - 8001:8001
    volumes:
      - ./redis_data:/data/redis

  api:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

    stdin_open: true
    tty: true

volumes:
  redis_data:
